# Generated by Django 3.2.25 on 2024-06-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
