# Generated by Django 3.2.25 on 2024-06-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_edit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='edit',
        ),
    ]
