# Generated by Django 3.2.25 on 2024-06-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20240624_1057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='car',
            new_name='cart',
        ),
    ]
