# Generated by Django 3.2.25 on 2024-06-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_rename_car_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='CartItem',
        ),
    ]
